name: Documentation

on:
  push:
    branches:
      - master
      - main
    paths:
      - "*.md"
      - docs/**
    workflow_dispatch:

jobs:
  build-doc:
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@main
        with:
          python-version: 3.x
          cache: true
      - name: Build pages
        run: |
          pdm install -G docs
          pdm run mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
