name: Documentation

on:
  push:
    branches:
      - master
      - main
    paths:
      - "*.md"
      - docs/**

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@main
        with:
          python-version: 3.x
          cache: true
      - name: Build pages
        run: |
          pdm install -s doc
          pdm run mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
